<?php

namespace Database\Seeders;

use App\Models\Listing;
use Illuminate\Database\Seeder;

class ListingSeeder extends Seeder
{
  public function run(): void
  {
    $listings = [
      [
        'user_id' => 1,
        'type' => 'stays',
        'title' => 'Maison bretonne face à l\'océan',
        'photos' => ["https://images.unsplash.com/photo-1763226950354-b04f6101acd1?w=1200&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmlsbGElMjBjJUMzJUI0dGUlMjBkJ2F6dXJ8ZW58MHx8MHx8fDI%3D", "https://images.unsplash.com/photo-1763505972543-801354be1e5f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHZpbGxhJTIwYyVDMyVCNHRlJTIwZCdhenVyfGVufDB8fDB8fHwy", "https://images.unsplash.com/photo-1719297491193-5fd6a4d04467?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHZpbGxhJTIwYmVkcm9vbXxlbnwwfHwwfHx8MA%3D%3D"],
        'description' => 'Charmante maison en pierre à deux pas de la plage. Contact direct avec la propriétaire pour organiser votre séjour.',
        'price_amount' => 110.00,
        'price_unit' => 'night',
        'capacity' => 5,
        'min_duration' => 2,
        'max_duration' => 30,
        'duration_unit' => 'night',
        'country' => 'FR',
        'region' => 'Bretagne',
        'city' => 'Quiberon',
        'tags' => ['bord-de-mer', 'maison-entière', 'famille'],
        'address' => '8 Rue de la Côte Sauvage',
        'latitude' => 47.4844,
        'longitude' => -3.1198,
        'location_display' => 'exact',
        'contact_email' => 'lois@morgates.com',
        'contact_phone' => '+33600000001',
        'contact_whatsapp' => '+33600000001',
      ],
      [
        'user_id' => 1,
        'type' => 'stays',
        'title' => 'Appartement lumineux dans le centre de Rennes',
        'photos' => ["https://plus.unsplash.com/premium_photo-1682377521385-bb04165dc742?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8dmlsbGElMjBiZWRyb29tfGVufDB8fDB8fHww", "https://images.unsplash.com/photo-1613977257365-aaae5a9817ff?w=300&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dmlsbGF8ZW58MHx8MHx8fDI%3D", "https://images.unsplash.com/photo-1602774895672-b553538bceb9?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDd8fHxlbnwwfHx8fHw%3D"],
        'description' => 'Appartement calme proche des commerces et des transports. La réservation se fait directement avec le propriétaire.',
        'price_amount' => 82.00,
        'price_unit' => 'night',
        'capacity' => 3,
        'min_duration' => 2,
        'max_duration' => 14,
        'duration_unit' => 'night',
        'country' => 'FR',
        'region' => 'Bretagne',
        'city' => 'Rennes',
        'tags' => ['centre-ville', 'wifi', 'court-séjour'],
        'address' => '12 Rue Saint-Michel',
        'latitude' => 48.1135,
        'longitude' => -1.6780,
        'location_display' => 'exact',
        'contact_email' => 'alice@morgates.com',
        'contact_website' => 'https://example.com/contact-rennes',
      ],
      [
        'user_id' => 1,
        'type' => 'stays',
        'title' => 'Chalet montagne tout confort',
        'photos' => ["https://images.unsplash.com/photo-1709508496457-e2f9c42493c6?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hhbGV0JTIwbW9udGFnbmV8ZW58MHx8MHx8fDA%3D", "https://plus.unsplash.com/premium_photo-1680098056978-3ec146d6df14?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y2hhbGV0JTIwbW9udGFnbmV8ZW58MHx8MHx8fDA%3D"],
        'description' => 'Chalet cosy avec cheminée et accès direct aux sentiers. Échange direct avec l\'hôte avant de confirmer.',
        'price_amount' => 220.00,
        'price_unit' => 'night',
        'capacity' => 10,
        'min_duration' => 2,
        'max_duration' => 10,
        'duration_unit' => 'night',
        'country' => 'FR',
        'region' => 'Auvergne-Rhône-Alpes',
        'city' => 'Chamonix',
        'address' => '3 Route du Mont-Blanc',
        'tags' => ['vue-montagne', 'cheminée', 'famille'],
        'latitude' => 45.9237,
        'longitude' => 6.8694,
        'location_display' => 'area',
        'location_radius' => 3000,
        'contact_email' => 'kj@morgates.com',
        'contact_phone' => '+33600000003',
      ],
      [
        'user_id' => 1,
        'type' => 'stays',
        'title' => 'Cabane simple près du Golfe du Morbihan',
        'photos' => ["https://plus.unsplash.com/premium_photo-1670360414882-4d4e261afb53?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fHZpbGxhJTIwYmVkcm9vbXxlbnwwfHwwfHx8MA%3D%3D", "https://images.unsplash.com/photo-1760290015338-b83bf248e299?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bWFpc29uJTIwYnJldG9ubmV8ZW58MHx8MHx8fDA%3D", "https://images.unsplash.com/photo-1616350428103-cc6bf12d46f0?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnJldGFnbmV8ZW58MHx8MHx8fDA%3D"],
        'description' => 'Petit hébergement indépendant pour se poser quelques jours au calme, sans plateforme de réservation intermédiaire.',
        'price_amount' => 65.00,
        'price_unit' => 'night',
        'capacity' => 2,
        'min_duration' => 1,
        'max_duration' => 7,
        'duration_unit' => 'night',
        'country' => 'FR',
        'region' => 'Bretagne',
        'city' => 'Vannes',
        'tags' => ['calme', 'nature', 'couple'],
        'address' => '4 Chemin des Salines',
        'latitude' => 47.6582,
        'longitude' => -2.7608,
        'location_display' => 'area',
        'location_radius' => 1000,
        'contact_phone' => '+33600000004',
      ],
      [
        'user_id' => 1,
        'type' => 'boats',
        'title' => 'Sortie en voilier dans la baie de Quiberon',
        'photos' => ["https://images.unsplash.com/photo-1498623116890-37e912163d5d?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHZvaWxpZXJ8ZW58MHx8MHx8fDA%3D"],
        'description' => 'Sortie côtière en petit groupe avec skipper local. Contact direct pour convenir de la date, du port et du programme.',
        'price_amount' => 90.00,
        'price_unit' => 'day',
        'capacity' => 4,
        'min_duration' => 1,
        'max_duration' => 1,
        'duration_unit' => 'day',
        'country' => 'FR',
        'region' => 'Bretagne',
        'city' => 'Quiberon',
        'tags' => ['voilier', 'skipper', 'demi-journée'],
        'address' => 'Port Haliguen',
        'latitude' => 47.4852,
        'longitude' => -3.0991,
        'location_display' => 'exact',
        'contact_email' => 'lois@morgates.com',
        'contact_whatsapp' => '+33600000001',
      ],
      [
        'user_id' => 1,
        'type' => 'boats',
        'title' => 'Journée catamaran au départ de Marseille',
        'photos' => ["https://images.unsplash.com/photo-1581271164789-7c97932822d3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2F0YW1hcmFufGVufDB8fDB8fHww"],
        'description' => 'Catamaran spacieux pour une sortie vers les calanques. Les conditions se règlent directement avec l\'équipage.',
        'price_amount' => 120.00,
        'price_unit' => 'day',
        'capacity' => 8,
        'min_duration' => 1,
        'max_duration' => 1,
        'duration_unit' => 'day',
        'country' => 'FR',
        'region' => 'Provence-Alpes-Côte d\'Azur',
        'city' => 'Marseille',
        'tags' => ['catamaran', 'calanques', 'groupe'],
        'address' => 'Vieux-Port',
        'latitude' => 43.2951,
        'longitude' => 5.3746,
        'location_display' => 'exact',
        'contact_email' => 'alice@morgates.com',
        'contact_website' => 'https://example.com/catamaran-marseille',
      ],
      [
        'user_id' => 1,
        'type' => 'boats',
        'title' => 'Balade en bateau moteur sur le lac d\'Annecy',
        'photos' => ["https://images.unsplash.com/photo-1510525009512-ad7fc13eefab?w=200&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGJhdGVhdXxlbnwwfHwwfHx8MA%3D%3D"],
        'description' => 'Bateau moteur idéal pour explorer le lac avec un propriétaire local. Contact direct par téléphone.',
        'price_amount' => 160.00,
        'price_unit' => 'trip',
        'capacity' => 6,
        'min_duration' => 1,
        'max_duration' => 1,
        'duration_unit' => 'day',
        'country' => 'FR',
        'region' => 'Auvergne-Rhône-Alpes',
        'city' => 'Annecy',
        'tags' => ['bateau-moteur', 'lac', 'famille'],
        'address' => 'Port d\'Annecy',
        'latitude' => 45.8992,
        'longitude' => 6.1294,
        'contact_phone' => '+33600000006',
      ],
      [
        'user_id' => 1,
        'type' => 'boats',
        'title' => 'Voilier habitable pour sortie à la journée',
        'photos' => ["https://images.unsplash.com/photo-1559213270-baa5ade97be6?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cCVDMyVBOW5pY2hlfGVufDB8fDB8fHww"],
        'description' => 'Voilier confortable pour découvrir la côte avec un marin expérimenté. Pas de réservation Morgates, échange direct uniquement.',
        'price_amount' => 250.00,
        'price_unit' => 'trip',
        'capacity' => 5,
        'min_duration' => 1,
        'max_duration' => 1,
        'duration_unit' => 'day',
        'country' => 'FR',
        'region' => 'Provence-Alpes-Côte d\'Azur',
        'city' => 'Antibes',
        'tags' => ['voilier', 'côte', 'skipper'],
        'address' => 'Port Vauban',
        'latitude' => 43.5804,
        'longitude' => 7.1282,
        'location_display' => 'area',
        'location_radius' => 5000,
        'contact_email' => 'kj@morgates.com',
        'contact_social_links' => ['https://instagram.com/morgates'],
      ],
    ];

    foreach ($listings as $listing) {
      Listing::create($listing);
    }
  }
}
