<?php

return [
  // stays
  'bord-de-mer'      => ['group' => 'stays', 'icon' => 'ripple',           'label' => 'Bord de mer'],
  'vue-mer'          => ['group' => 'stays', 'icon' => 'binoculars',        'label' => 'Vue mer'],
  'prive'            => ['group' => 'stays', 'icon' => 'lock',              'label' => 'Privé'],
  'jardin'           => ['group' => 'stays', 'icon' => 'flower',            'label' => 'Jardin'],
  'piscine'          => ['group' => 'stays', 'icon' => 'pool',              'label' => 'Piscine'],
  'jacuzzi'          => ['group' => 'stays', 'icon' => 'bath',              'label' => 'Jacuzzi'],
  'sauna'            => ['group' => 'stays', 'icon' => 'massage',           'label' => 'Sauna'],
  'accessible'       => ['group' => 'stays', 'icon' => 'wheelchair',        'label' => 'Accessible'],
  'animaux-acceptes' => ['group' => 'stays', 'icon' => 'dog',               'label' => 'Animaux acceptés'],
  'non-fumeur'       => ['group' => 'stays', 'icon' => 'smoking-no',        'label' => 'Non-fumeur'],
  'wifi'             => ['group' => 'stays', 'icon' => 'wifi',              'label' => 'Wi-Fi'],
  'parking'          => ['group' => 'stays', 'icon' => 'parking',           'label' => 'Parking'],
  'au-calme'         => ['group' => 'stays', 'icon' => 'moon',              'label' => 'Au calme'],
  'central'          => ['group' => 'stays', 'icon' => 'map-pin',           'label' => 'Central'],
  'famille'          => ['group' => 'stays', 'icon' => 'mood-kid',          'label' => 'Idéal famille'],
  'business'         => ['group' => 'stays', 'icon' => 'briefcase',         'label' => 'Équipé business'],
  'luxe'             => ['group' => 'stays', 'icon' => 'diamond',           'label' => 'Luxe'],
  'cuisine'          => ['group' => 'stays', 'icon' => 'cooker',            'label' => 'Cuisine équipée'],
  'climatisation'    => ['group' => 'stays', 'icon' => 'air-conditioning',  'label' => 'Clim'],
  'lave-linge'       => ['group' => 'stays', 'icon' => 'wash-machine',      'label' => 'Lave-linge'],
  'television'       => ['group' => 'stays', 'icon' => 'device-tv',         'label' => 'TV'],
  'chauffage'        => ['group' => 'stays', 'icon' => 'flame',             'label' => 'Chauffage'],
  'espace-travail'   => ['group' => 'stays', 'icon' => 'desk',              'label' => 'Espace travail'],
  'lit-bebe'         => ['group' => 'stays', 'icon' => 'baby-carriage',     'label' => 'Lit bébé'],
  'barbecue'         => ['group' => 'stays', 'icon' => 'grill',             'label' => 'Barbecue'],
  'cheminee'         => ['group' => 'stays', 'icon' => 'flame',             'label' => 'Cheminée'],

  // boats
  'skipper'             => ['group' => 'boats', 'icon' => 'user-star',        'label' => 'Avec skipper'],
  'sans-skipper'        => ['group' => 'boats', 'icon' => 'anchor',           'label' => 'Sans skipper'],
  'coucher'             => ['group' => 'boats', 'icon' => 'bed',              'label' => 'Couchages'],
  'week-end'            => ['group' => 'boats', 'icon' => 'calendar-check',   'label' => 'Week-end'],
  'port'                => ['group' => 'boats', 'icon' => 'ship',             'label' => 'Au port'],
  'ile'                 => ['group' => 'boats', 'icon' => 'map',              'label' => 'Vers îles / côtes'],
  'peche'               => ['group' => 'boats', 'icon' => 'fish',             'label' => 'Pêche'],
  'plaisir'             => ['group' => 'boats', 'icon' => 'ship',             'label' => 'Plaisir / balade'],
  'jet-ski'             => ['group' => 'boats', 'icon' => 'speedboat',        'label' => 'Jet-ski'],
  'gps'                 => ['group' => 'boats', 'icon' => 'gps',              'label' => 'GPS'],
  'pilote-automatique'  => ['group' => 'boats', 'icon' => 'steering-wheel',   'label' => 'Pilote auto'],
  'vhf'                 => ['group' => 'boats', 'icon' => 'antenna-bars-5',   'label' => 'VHF'],
  'annexe'              => ['group' => 'boats', 'icon' => 'lifebuoy',         'label' => 'Annexe'],
  'paddle'              => ['group' => 'boats', 'icon' => 'ripple',           'label' => 'Paddle'],
  'kayak'               => ['group' => 'boats', 'icon' => 'kayak',            'label' => 'Kayak'],
  'plongee'             => ['group' => 'boats', 'icon' => 'scuba-mask',       'label' => 'Plongée'],
  'douche-pont'         => ['group' => 'boats', 'icon' => 'droplets',         'label' => 'Douche pont'],
  'panneaux-solaires'   => ['group' => 'boats', 'icon' => 'solar-panel',      'label' => 'Solaire'],
];
