<?php

return [
  // stays
  'bord-de-mer' => ['icon' => 'waves', 'label' => 'Bord de mer'],
  'vue-mer' => ['icon' => 'binoculars', 'label' => 'Vue mer'],
  'prive' => ['icon' => 'lock', 'label' => 'Privé'],
  'jardin' => ['icon' => 'flower', 'label' => 'Jardin'],
  'piscine' => ['icon' => 'pool', 'label' => 'Piscine'],
  'jacuzzi' => ['icon' => 'bath', 'label' => 'Jacuzzi'],
  'sauna' => ['icon' => 'spa', 'label' => 'Sauna'],
  'accessible' => ['icon' => 'wheelchair', 'label' => 'Accessible'],
  'animaux-acceptes' => ['icon' => 'dog', 'label' => 'Animaux acceptés'],
  'non-fumeur' => ['icon' => 'smoking-no', 'label' => 'Non-fumeur'],
  'wifi' => ['icon' => 'wifi', 'label' => 'Wi-Fi'],
  'parking' => ['icon' => 'parking', 'label' => 'Parking'],
  'au-calme' => ['icon' => 'moon', 'label' => 'Au calme'],
  'central' => ['icon' => 'map-pin', 'label' => 'Central'],
  'famille' => ['icon' => 'child', 'label' => 'Idéal famille'],
  'business' => ['icon' => 'briefcase', 'label' => 'Équipé business'],
  'luxe' => ['icon' => 'gem', 'label' => 'Luxe'],
  'cuisine' => ['icon' => 'cooker', 'label' => 'Cuisine équipée'],
  'climatisation' => ['icon' => 'air-conditioning', 'label' => 'Clim'],
  'lave-linge' => ['icon' => 'washing-machine', 'label' => 'Lave-linge'],
  'television' => ['icon' => 'device-tv', 'label' => 'TV'],
  'chauffage' => ['icon' => 'heater', 'label' => 'Chauffage'],
  'espace-travail' => ['icon' => 'desk', 'label' => 'Espace travail'],
  'lit-bebe' => ['icon' => 'crib', 'label' => 'Lit bébé'],
  'barbecue' => ['icon' => 'barbecue', 'label' => 'Barbecue'],
  'cheminee' => ['icon' => 'fireplace', 'label' => 'Cheminée'],

  // boats
  'skipper' => ['icon' => 'user-tie', 'label' => 'Avec skipper'],
  'sans-skipper' => ['icon' => 'anchor', 'label' => 'Sans skipper'],
  'coucher' => ['icon' => 'bed', 'label' => 'Couchages'],
  'week-end' => ['icon' => 'calendar-check', 'label' => 'Week-end'],
  'port' => ['icon' => 'ship', 'label' => 'Au port'],
  'ile' => ['icon' => 'map', 'label' => 'Vers îles / côtes'],
  'peche' => ['icon' => 'fish', 'label' => 'Pêche'],
  'plaisir' => ['icon' => 'ship', 'label' => 'Plaisir / balade'],
  'jet-ski' => ['icon' => 'jetski', 'label' => 'Jet-ski'],
  'gps' => ['icon' => 'gps', 'label' => 'GPS'],
  'pilote-automatique' => ['icon' => 'steering-wheel', 'label' => 'Pilote auto'],
  'vhf' => ['icon' => 'antenna-bars-5', 'label' => 'VHF'],
  'annexe' => ['icon' => 'boat', 'label' => 'Annexe'],
  'paddle' => ['icon' => 'oar', 'label' => 'Paddle'],
  'kayak' => ['icon' => 'kayak', 'label' => 'Kayak'],
  'plongee' => ['icon' => 'scuba-mask', 'label' => 'Plongée'],
  'douche-pont' => ['icon' => 'shower', 'label' => 'Douche pont'],
  'panneaux-solaires' => ['icon' => 'solar-panel', 'label' => 'Solaire'],
];